<?php
/**
 * @file
 * SEC_User Table Seeder
 *
 * All DecimaAccounting code is copyright by the original authors and released under the GNU Aferro General Public License version 3 (AGPLv3) or later.
 * See COPYRIGHT and LICENSE.
 */

namespace Mgallegos\DecimaAccounting\System\Seeders;

use DB;
use Illuminate\Database\Seeder;
use Mgallegos\DecimaAccounting\System\Account;

class AccountSlvTableSeeder extends Seeder {

	public function run()
	{
		Account::create(array('name' => 'ACTIVO', 'key' => '1', 'parent_key' => '', 'balance_type' => 'D', 'account_type_key' => 'A', 'is_group' => 1, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'ACTIVO CORRIENTE', 'key' => '11', 'parent_key' => '1', 'balance_type' => 'D', 'account_type_key' => 'A', 'is_group' => 1, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'EFECTIVO Y EQUIVALENTES', 'key' => '1101', 'parent_key' => '11', 'balance_type' => 'D', 'account_type_key' => 'A', 'is_group' => 1, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'CAJA', 'key' => '110101', 'parent_key' => '1101', 'balance_type' => 'D', 'account_type_key' => 'A', 'is_group' => 1, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'Caja General', 'key' => '11010101', 'parent_key' => '110101', 'balance_type' => 'D', 'account_type_key' => 'A', 'is_group' => 0, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'Caja Chica', 'key' => '11010102', 'parent_key' => '110101', 'balance_type' => 'D', 'account_type_key' => 'A', 'is_group' => 0, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'BANCOS', 'key' => '110102', 'parent_key' => '1101', 'balance_type' => 'D', 'account_type_key' => 'A', 'is_group' => 1, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'CUENTAS CORRIENTES', 'key' => '11010201', 'parent_key' => '110102', 'balance_type' => 'D', 'account_type_key' => 'A', 'is_group' => 1, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'Cuenta Corriente Banco Agrícola #', 'key' => '1101020101', 'parent_key' => '11010201', 'balance_type' => 'D', 'account_type_key' => 'A', 'is_group' => 0, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'Cuenta Corriente Banco Davivienda #', 'key' => '1101020102', 'parent_key' => '11010201', 'balance_type' => 'D', 'account_type_key' => 'A', 'is_group' => 0, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'Cuenta Corriente Banco Citibank #', 'key' => '1101020103', 'parent_key' => '11010201', 'balance_type' => 'D', 'account_type_key' => 'A', 'is_group' => 0, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'Cuenta Corriente Banco Scotiabank #', 'key' => '1101020104', 'parent_key' => '11010201', 'balance_type' => 'D', 'account_type_key' => 'A', 'is_group' => 0, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'Cuenta Corriente Banco América Central #', 'key' => '1101020105', 'parent_key' => '11010201', 'balance_type' => 'D', 'account_type_key' => 'A', 'is_group' => 0, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'CUENTAS DE AHORRO', 'key' => '11010202', 'parent_key' => '110102', 'balance_type' => 'D', 'account_type_key' => 'A', 'is_group' => 1, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'Cuenta de Ahorro Banco Agrícola  #', 'key' => '1101020201', 'parent_key' => '11010202', 'balance_type' => 'D', 'account_type_key' => 'A', 'is_group' => 0, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'Cuenta de Ahorro Banco Davivienda #', 'key' => '1101020202', 'parent_key' => '11010202', 'balance_type' => 'D', 'account_type_key' => 'A', 'is_group' => 0, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'Cuenta de Ahorro Banco Citibank #', 'key' => '1101020203', 'parent_key' => '11010202', 'balance_type' => 'D', 'account_type_key' => 'A', 'is_group' => 0, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'Cuenta de Ahorro Banco Scotiabank #', 'key' => '1101020204', 'parent_key' => '11010202', 'balance_type' => 'D', 'account_type_key' => 'A', 'is_group' => 0, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'Cuenta de Ahorro Banco América Central #', 'key' => '1101020205', 'parent_key' => '11010202', 'balance_type' => 'D', 'account_type_key' => 'A', 'is_group' => 0, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'DEPÓSITOS A PLAZO (menores a tres meses plazo)', 'key' => '11010203', 'parent_key' => '110102', 'balance_type' => 'D', 'account_type_key' => 'A', 'is_group' => 1, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'Depósitos a Plazo Banco Agrícola', 'key' => '1101020301', 'parent_key' => '11010203', 'balance_type' => 'D', 'account_type_key' => 'A', 'is_group' => 0, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'Depósitos a Plazo Banco Davivienda', 'key' => '1101020302', 'parent_key' => '11010203', 'balance_type' => 'D', 'account_type_key' => 'A', 'is_group' => 0, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'Depósitos a Plazo Banco Citibank', 'key' => '1101020303', 'parent_key' => '11010203', 'balance_type' => 'D', 'account_type_key' => 'A', 'is_group' => 0, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'Depósitos a Plazo Banco Scotiabank ', 'key' => '1101020304', 'parent_key' => '11010203', 'balance_type' => 'D', 'account_type_key' => 'A', 'is_group' => 0, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'Depósitos a PlazoBanco América Central', 'key' => '1101020305', 'parent_key' => '11010203', 'balance_type' => 'D', 'account_type_key' => 'A', 'is_group' => 0, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'EQUIVALENTES DE EFECTIVO', 'key' => '110103', 'parent_key' => '1101', 'balance_type' => 'D', 'account_type_key' => 'A', 'is_group' => 1, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'Reportos', 'key' => '11010301', 'parent_key' => '110103', 'balance_type' => 'D', 'account_type_key' => 'A', 'is_group' => 0, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'CUENTAS Y DOCUMENTOS POR COBRAR', 'key' => '1102', 'parent_key' => '11', 'balance_type' => 'D', 'account_type_key' => 'A', 'is_group' => 1, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'Cuentas por Cobrar Comerciales Locales', 'key' => '110201', 'parent_key' => '1102', 'balance_type' => 'D', 'account_type_key' => 'A', 'is_group' => 0, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'Cuentas por Cobrar Comerciales del Exterior', 'key' => '110202', 'parent_key' => '1102', 'balance_type' => 'D', 'account_type_key' => 'A', 'is_group' => 0, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'Préstamos a Funcionarios y Empleados', 'key' => '110203', 'parent_key' => '1102', 'balance_type' => 'D', 'account_type_key' => 'A', 'is_group' => 0, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'Otras Cuentas por Cobrar', 'key' => '110204', 'parent_key' => '1102', 'balance_type' => 'D', 'account_type_key' => 'A', 'is_group' => 0, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'ESTIMACIÓN (DETERIORO) PARA CUENTAS INCOBRABLES', 'key' => '1103', 'parent_key' => '11', 'balance_type' => 'A', 'account_type_key' => 'A', 'is_group' => 1, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'Estimación (Derioro) para Cuentas Incobrables', 'key' => '110301', 'parent_key' => '1103', 'balance_type' => 'A', 'account_type_key' => 'A', 'is_group' => 0, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'CUENTAS POR COBRAR – PARTES RELACIONADAS', 'key' => '1104', 'parent_key' => '11', 'balance_type' => 'D', 'account_type_key' => 'A', 'is_group' => 1, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'Cuenta por Cobrar a Directores y Ejecutivos', 'key' => '110401', 'parent_key' => '1104', 'balance_type' => 'D', 'account_type_key' => 'A', 'is_group' => 0, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'Cuentas por cobrar a Compañías Subsidiarias', 'key' => '110402', 'parent_key' => '1104', 'balance_type' => 'D', 'account_type_key' => 'A', 'is_group' => 0, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'ACCIONISTAS', 'key' => '1105', 'parent_key' => '11', 'balance_type' => 'D', 'account_type_key' => 'A', 'is_group' => 1, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'Acciones Suscritas no Pagadas', 'key' => '110501', 'parent_key' => '1105', 'balance_type' => 'D', 'account_type_key' => 'A', 'is_group' => 0, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'INVENTARIOS', 'key' => '1106', 'parent_key' => '11', 'balance_type' => 'D', 'account_type_key' => 'A', 'is_group' => 1, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'Inventario de Productos Terminados ', 'key' => '110601', 'parent_key' => '1106', 'balance_type' => 'D', 'account_type_key' => 'A', 'is_group' => 0, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'Inventario de Productos en Proceso', 'key' => '110602', 'parent_key' => '1106', 'balance_type' => 'D', 'account_type_key' => 'A', 'is_group' => 0, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'Inventario de Materiales ', 'key' => '110603', 'parent_key' => '1106', 'balance_type' => 'D', 'account_type_key' => 'A', 'is_group' => 0, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'Inventario de Insumos', 'key' => '110604', 'parent_key' => '1106', 'balance_type' => 'D', 'account_type_key' => 'A', 'is_group' => 0, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'Otros Inventarios', 'key' => '110605', 'parent_key' => '1106', 'balance_type' => 'D', 'account_type_key' => 'A', 'is_group' => 0, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'INVERSIONES A CORTO PLAZO', 'key' => '1107', 'parent_key' => '11', 'balance_type' => 'D', 'account_type_key' => 'A', 'is_group' => 1, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'Depósitos a Plazo (mayor a tres meses plazo)', 'key' => '110701', 'parent_key' => '1107', 'balance_type' => 'D', 'account_type_key' => 'A', 'is_group' => 0, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'Acciones', 'key' => '110702', 'parent_key' => '1107', 'balance_type' => 'D', 'account_type_key' => 'A', 'is_group' => 0, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'Otras Inversiones a corto plazo', 'key' => '110703', 'parent_key' => '1107', 'balance_type' => 'D', 'account_type_key' => 'A', 'is_group' => 0, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'GASTOS PAGADOS POR ANTICIPADO', 'key' => '1108', 'parent_key' => '11', 'balance_type' => 'D', 'account_type_key' => 'A', 'is_group' => 1, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'Seguros Pagados por Anticipado', 'key' => '110801', 'parent_key' => '1108', 'balance_type' => 'D', 'account_type_key' => 'A', 'is_group' => 0, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'Inventario de Papelería y Útiles', 'key' => '110802', 'parent_key' => '1108', 'balance_type' => 'D', 'account_type_key' => 'A', 'is_group' => 0, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'Alquileres Pagados por Anticipado', 'key' => '110803', 'parent_key' => '1108', 'balance_type' => 'D', 'account_type_key' => 'A', 'is_group' => 0, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'PAGO A CUENTA', 'key' => '1109', 'parent_key' => '11', 'balance_type' => 'D', 'account_type_key' => 'A', 'is_group' => 1, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'Pago a Cuenta ISR', 'key' => '110901', 'parent_key' => '1109', 'balance_type' => 'D', 'account_type_key' => 'A', 'is_group' => 0, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'Retenciones de ISR', 'key' => '110902', 'parent_key' => '1109', 'balance_type' => 'D', 'account_type_key' => 'A', 'is_group' => 0, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'CRÉDITO FISCAL – I V A', 'key' => '1110', 'parent_key' => '11', 'balance_type' => 'D', 'account_type_key' => 'A', 'is_group' => 1, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'Crédito Fiscal sobre Compras - IVA', 'key' => '111001', 'parent_key' => '1110', 'balance_type' => 'D', 'account_type_key' => 'A', 'is_group' => 0, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'Retenciones de IVA', 'key' => '111002', 'parent_key' => '1110', 'balance_type' => 'D', 'account_type_key' => 'A', 'is_group' => 0, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'REMANENTE DE IVA', 'key' => '1111', 'parent_key' => '11', 'balance_type' => 'D', 'account_type_key' => 'A', 'is_group' => 1, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'Remanente de IVA ', 'key' => '111101', 'parent_key' => '1111', 'balance_type' => 'D', 'account_type_key' => 'A', 'is_group' => 0, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'ACTIVO NO CORRIENTE', 'key' => '12', 'parent_key' => '1', 'balance_type' => 'D', 'account_type_key' => 'A', 'is_group' => 1, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'PROPIEDADES PLANTA Y EQUIPO', 'key' => '1201', 'parent_key' => '12', 'balance_type' => 'D', 'account_type_key' => 'A', 'is_group' => 1, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'Terrenos', 'key' => '120101', 'parent_key' => '1201', 'balance_type' => 'D', 'account_type_key' => 'A', 'is_group' => 0, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'Edificios', 'key' => '120102', 'parent_key' => '1201', 'balance_type' => 'D', 'account_type_key' => 'A', 'is_group' => 0, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'Construcciones', 'key' => '120103', 'parent_key' => '1201', 'balance_type' => 'D', 'account_type_key' => 'A', 'is_group' => 0, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'Maquinaria ', 'key' => '120104', 'parent_key' => '1201', 'balance_type' => 'D', 'account_type_key' => 'A', 'is_group' => 0, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'Mobiliario', 'key' => '120105', 'parent_key' => '1201', 'balance_type' => 'D', 'account_type_key' => 'A', 'is_group' => 0, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'Equipo ', 'key' => '120106', 'parent_key' => '1201', 'balance_type' => 'D', 'account_type_key' => 'A', 'is_group' => 0, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'Vehículos', 'key' => '120107', 'parent_key' => '1201', 'balance_type' => 'D', 'account_type_key' => 'A', 'is_group' => 0, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'Herramientas ', 'key' => '120108', 'parent_key' => '1201', 'balance_type' => 'D', 'account_type_key' => 'A', 'is_group' => 0, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'Instalaciones', 'key' => '120109', 'parent_key' => '1201', 'balance_type' => 'D', 'account_type_key' => 'A', 'is_group' => 0, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'Otros bienes', 'key' => '120110', 'parent_key' => '1201', 'balance_type' => 'D', 'account_type_key' => 'A', 'is_group' => 0, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'PROPIEDADES DE INVERSIÓN', 'key' => '1202', 'parent_key' => '12', 'balance_type' => 'D', 'account_type_key' => 'A', 'is_group' => 1, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'Propiedades de Inversión Terrenos', 'key' => '120201', 'parent_key' => '1202', 'balance_type' => 'D', 'account_type_key' => 'A', 'is_group' => 0, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'Propiedades de Inversión Edificios', 'key' => '120202', 'parent_key' => '1202', 'balance_type' => 'D', 'account_type_key' => 'A', 'is_group' => 0, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'PROPIEDADES PLANTA Y EQUIPO – EN ARRENDAMIENTO FINANCIERO', 'key' => '1203', 'parent_key' => '12', 'balance_type' => 'D', 'account_type_key' => 'A', 'is_group' => 1, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'Maquinaria y Equipo en Arrendamiento Financiero', 'key' => '120301', 'parent_key' => '1203', 'balance_type' => 'D', 'account_type_key' => 'A', 'is_group' => 0, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'Mobiliario y Equipo de Oficina en Arrendamiento Financiero', 'key' => '120302', 'parent_key' => '1203', 'balance_type' => 'D', 'account_type_key' => 'A', 'is_group' => 0, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'Equipo de Transporte en Arrendamiento Financiero', 'key' => '120303', 'parent_key' => '1203', 'balance_type' => 'D', 'account_type_key' => 'A', 'is_group' => 0, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'Otros Equipos en Arrendamiento Financiero', 'key' => '120304', 'parent_key' => '1203', 'balance_type' => 'D', 'account_type_key' => 'A', 'is_group' => 0, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'DEPRECIACIÓN ACUMULADA – PROPIEDADES PLANTA Y EQUIPO', 'key' => '1204', 'parent_key' => '12', 'balance_type' => 'A', 'account_type_key' => 'A', 'is_group' => 1, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'Depreciación Acumulada de Edificios', 'key' => '120401', 'parent_key' => '1204', 'balance_type' => 'A', 'account_type_key' => 'A', 'is_group' => 0, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'Depreciación Acumulada de Construcciones', 'key' => '120402', 'parent_key' => '1204', 'balance_type' => 'A', 'account_type_key' => 'A', 'is_group' => 0, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'Depreciación Acumulada de Maquinaria ', 'key' => '120403', 'parent_key' => '1204', 'balance_type' => 'A', 'account_type_key' => 'A', 'is_group' => 0, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'Depreciación Acumulada de Mobiliario', 'key' => '120404', 'parent_key' => '1204', 'balance_type' => 'A', 'account_type_key' => 'A', 'is_group' => 0, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'Depreciación Acumulada de Equipo ', 'key' => '120405', 'parent_key' => '1204', 'balance_type' => 'A', 'account_type_key' => 'A', 'is_group' => 0, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'Depreciación Acumulada de Vehiculos', 'key' => '120406', 'parent_key' => '1204', 'balance_type' => 'A', 'account_type_key' => 'A', 'is_group' => 0, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'Depreciación Acumulada de Herramientas ', 'key' => '120407', 'parent_key' => '1204', 'balance_type' => 'A', 'account_type_key' => 'A', 'is_group' => 0, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'Depreciación Acumulada de Instalaciones', 'key' => '120408', 'parent_key' => '1204', 'balance_type' => 'A', 'account_type_key' => 'A', 'is_group' => 0, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'Depreciación Acumulada Otros bienes', 'key' => '120409', 'parent_key' => '1204', 'balance_type' => 'A', 'account_type_key' => 'A', 'is_group' => 0, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'DEPRECIACIÓN ACUMULADA – PROPIEDADES, PLANTA Y EQUIPO  - EN ARRENDAMIENTO FINANCIERO', 'key' => '1205', 'parent_key' => '12', 'balance_type' => 'A', 'account_type_key' => 'A', 'is_group' => 1, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'Depreciación Acumulada de Maquinaria y Equipo en A. F.', 'key' => '120501', 'parent_key' => '1205', 'balance_type' => 'A', 'account_type_key' => 'A', 'is_group' => 0, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'Depreciación Acumulada de Mobiliario y Equipo de Oficina en A. F.', 'key' => '120502', 'parent_key' => '1205', 'balance_type' => 'A', 'account_type_key' => 'A', 'is_group' => 0, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'Depreciación Acumulada de Equipo de Transporte en A. F.', 'key' => '120503', 'parent_key' => '1205', 'balance_type' => 'A', 'account_type_key' => 'A', 'is_group' => 0, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'Depreciación Acumulada de Otros Equipos en A. F.', 'key' => '120504', 'parent_key' => '1205', 'balance_type' => 'A', 'account_type_key' => 'A', 'is_group' => 0, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'ACTIVOS  EN DESARROLLO', 'key' => '1206', 'parent_key' => '12', 'balance_type' => 'D', 'account_type_key' => 'A', 'is_group' => 1, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'Software en Desarrollo', 'key' => '120601', 'parent_key' => '1206', 'balance_type' => 'D', 'account_type_key' => 'A', 'is_group' => 0, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'Otros Intangibles en Desarrollo', 'key' => '120602', 'parent_key' => '1206', 'balance_type' => 'D', 'account_type_key' => 'A', 'is_group' => 0, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'CUENTAS POR COBRAR A LARGO PLAZO', 'key' => '1207', 'parent_key' => '12', 'balance_type' => 'D', 'account_type_key' => 'A', 'is_group' => 1, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'Cuentas por Cobrar a Largo Plazo', 'key' => '120701', 'parent_key' => '1207', 'balance_type' => 'D', 'account_type_key' => 'A', 'is_group' => 0, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'INVERSIONES PERMANENTES', 'key' => '1208', 'parent_key' => '12', 'balance_type' => 'D', 'account_type_key' => 'A', 'is_group' => 1, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'Inversiones en Subsidiarias', 'key' => '120801', 'parent_key' => '1208', 'balance_type' => 'D', 'account_type_key' => 'A', 'is_group' => 0, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'Inversiones en Asociadas', 'key' => '120802', 'parent_key' => '1208', 'balance_type' => 'D', 'account_type_key' => 'A', 'is_group' => 0, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'Otras Inversiones Permanentes', 'key' => '120803', 'parent_key' => '1208', 'balance_type' => 'D', 'account_type_key' => 'A', 'is_group' => 0, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'INTANGIBLES', 'key' => '1209', 'parent_key' => '12', 'balance_type' => 'D', 'account_type_key' => 'A', 'is_group' => 1, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'Derecho de Llave', 'key' => '120901', 'parent_key' => '1209', 'balance_type' => 'D', 'account_type_key' => 'A', 'is_group' => 0, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'Patentes y Marcas', 'key' => '120902', 'parent_key' => '1209', 'balance_type' => 'D', 'account_type_key' => 'A', 'is_group' => 0, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'Franquicias', 'key' => '120903', 'parent_key' => '1209', 'balance_type' => 'D', 'account_type_key' => 'A', 'is_group' => 0, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'Licencias y Concesiones', 'key' => '120904', 'parent_key' => '1209', 'balance_type' => 'D', 'account_type_key' => 'A', 'is_group' => 0, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'Programas y Sistemas', 'key' => '120905', 'parent_key' => '1209', 'balance_type' => 'D', 'account_type_key' => 'A', 'is_group' => 0, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'AMORTIZACIÓN ACUMULADA DE ACTIVOS INTANGIBLES', 'key' => '1210', 'parent_key' => '12', 'balance_type' => 'A', 'account_type_key' => 'A', 'is_group' => 1, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'Amortización Acumulada de Derecho de Llave', 'key' => '121001', 'parent_key' => '1210', 'balance_type' => 'A', 'account_type_key' => 'A', 'is_group' => 0, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'Amortización Acumulada de Patentes y Marcas', 'key' => '121002', 'parent_key' => '1210', 'balance_type' => 'A', 'account_type_key' => 'A', 'is_group' => 0, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'Amortización Acumulada de Franquicias', 'key' => '121003', 'parent_key' => '1210', 'balance_type' => 'A', 'account_type_key' => 'A', 'is_group' => 0, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'Amortización Acumulada de Licencias y Concesiones', 'key' => '121004', 'parent_key' => '1210', 'balance_type' => 'A', 'account_type_key' => 'A', 'is_group' => 0, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'Amortización Acumulada de Programas y Sistemas', 'key' => '121005', 'parent_key' => '1210', 'balance_type' => 'A', 'account_type_key' => 'A', 'is_group' => 0, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'DEPÓSITOS EN GARANTÍA', 'key' => '1211', 'parent_key' => '12', 'balance_type' => 'D', 'account_type_key' => 'A', 'is_group' => 1, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'Depósitos en Garantía por Alquileres', 'key' => '121101', 'parent_key' => '1211', 'balance_type' => 'D', 'account_type_key' => 'A', 'is_group' => 0, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'ACTIVO POR IMPUESTO SOBRE LA RENTA DIFERIDO', 'key' => '1212', 'parent_key' => '12', 'balance_type' => 'D', 'account_type_key' => 'A', 'is_group' => 1, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'Activo por Impuesto sobre la Renta Diferido', 'key' => '121201', 'parent_key' => '1212', 'balance_type' => 'D', 'account_type_key' => 'A', 'is_group' => 0, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'PASIVO', 'key' => '2', 'parent_key' => '', 'balance_type' => 'A', 'account_type_key' => 'P', 'is_group' => 1, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'PASIVO CORRIENTE', 'key' => '21', 'parent_key' => '2', 'balance_type' => 'A', 'account_type_key' => 'P', 'is_group' => 1, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'PRÉSTAMOS A CORTO PLAZO Y SOBREGIROS BANCARIOS', 'key' => '2101', 'parent_key' => '21', 'balance_type' => 'A', 'account_type_key' => 'P', 'is_group' => 1, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'Sobregiros Bancarios', 'key' => '210101', 'parent_key' => '2101', 'balance_type' => 'A', 'account_type_key' => 'P', 'is_group' => 0, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'Préstamos Bancarios (Porción a Corto Plazo)', 'key' => '210102', 'parent_key' => '2101', 'balance_type' => 'A', 'account_type_key' => 'P', 'is_group' => 0, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'Préstamos Personales (Porción a Corto Plazo)', 'key' => '210103', 'parent_key' => '2101', 'balance_type' => 'A', 'account_type_key' => 'P', 'is_group' => 0, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'CUENTAS Y DOCUMENTOS POR PAGAR', 'key' => '2102', 'parent_key' => '21', 'balance_type' => 'A', 'account_type_key' => 'P', 'is_group' => 1, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'Proveedores', 'key' => '210201', 'parent_key' => '2102', 'balance_type' => 'A', 'account_type_key' => 'P', 'is_group' => 0, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'Cuentas por Pagar', 'key' => '210202', 'parent_key' => '2102', 'balance_type' => 'A', 'account_type_key' => 'P', 'is_group' => 0, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'Documentos por Pagar', 'key' => '210203', 'parent_key' => '2102', 'balance_type' => 'A', 'account_type_key' => 'P', 'is_group' => 0, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'BENEFICIOS A EMPLEADOS POR PAGAR', 'key' => '210204', 'parent_key' => '2102', 'balance_type' => 'A', 'account_type_key' => 'P', 'is_group' => 1, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'Sueldos y Comisiones por Pagar', 'key' => '21020401', 'parent_key' => '210204', 'balance_type' => 'A', 'account_type_key' => 'P', 'is_group' => 0, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'Vacaciones por Pagar', 'key' => '21020402', 'parent_key' => '210204', 'balance_type' => 'A', 'account_type_key' => 'P', 'is_group' => 0, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'Aguinaldos por Pagar', 'key' => '21020403', 'parent_key' => '210204', 'balance_type' => 'A', 'account_type_key' => 'P', 'is_group' => 0, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'Indemnizaciones por Pagar', 'key' => '21020404', 'parent_key' => '210204', 'balance_type' => 'A', 'account_type_key' => 'P', 'is_group' => 0, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'Bonificaciones por Pagar', 'key' => '21020405', 'parent_key' => '210204', 'balance_type' => 'A', 'account_type_key' => 'P', 'is_group' => 0, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'Otras Prestaciones al Personal por Pagar', 'key' => '21020406', 'parent_key' => '210204', 'balance_type' => 'A', 'account_type_key' => 'P', 'is_group' => 0, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'ACREEDORES VARIOS', 'key' => '2103', 'parent_key' => '21', 'balance_type' => 'A', 'account_type_key' => 'P', 'is_group' => 1, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'Cuota Patronal ISSS / Salud', 'key' => '210301', 'parent_key' => '2103', 'balance_type' => 'A', 'account_type_key' => 'P', 'is_group' => 0, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'Cuota Patronal ISSS / Previsional', 'key' => '210302', 'parent_key' => '2103', 'balance_type' => 'A', 'account_type_key' => 'P', 'is_group' => 0, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'Cuota Patronal AFP', 'key' => '210303', 'parent_key' => '2103', 'balance_type' => 'A', 'account_type_key' => 'P', 'is_group' => 0, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'Intereses por Pagar', 'key' => '210304', 'parent_key' => '2103', 'balance_type' => 'A', 'account_type_key' => 'P', 'is_group' => 0, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'Honorarios por Pagar', 'key' => '210305', 'parent_key' => '2103', 'balance_type' => 'A', 'account_type_key' => 'P', 'is_group' => 0, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'IVA por Pagar', 'key' => '210306', 'parent_key' => '2103', 'balance_type' => 'A', 'account_type_key' => 'P', 'is_group' => 0, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'Impuestos Municipales por Pagar', 'key' => '210307', 'parent_key' => '2103', 'balance_type' => 'A', 'account_type_key' => 'P', 'is_group' => 0, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'Pago a Cuenta ISR por Pagar', 'key' => '210308', 'parent_key' => '2103', 'balance_type' => 'A', 'account_type_key' => 'P', 'is_group' => 0, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'Servicio de Energía Eléctrica por Pagar', 'key' => '210309', 'parent_key' => '2103', 'balance_type' => 'A', 'account_type_key' => 'P', 'is_group' => 0, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'RETENCIONES POR PAGAR', 'key' => '2104', 'parent_key' => '21', 'balance_type' => 'A', 'account_type_key' => 'P', 'is_group' => 1, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'Cotización ISSS / Salud', 'key' => '210401', 'parent_key' => '2104', 'balance_type' => 'A', 'account_type_key' => 'P', 'is_group' => 0, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'COTIZACIÓN A FONDO DE PENSIONES', 'key' => '210402', 'parent_key' => '2104', 'balance_type' => 'A', 'account_type_key' => 'P', 'is_group' => 1, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'ISSS Previsional', 'key' => '21040201', 'parent_key' => '210402', 'balance_type' => 'A', 'account_type_key' => 'P', 'is_group' => 0, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'AFP Crecer', 'key' => '21040202', 'parent_key' => '210402', 'balance_type' => 'A', 'account_type_key' => 'P', 'is_group' => 0, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'AFP Confía', 'key' => '21040203', 'parent_key' => '210402', 'balance_type' => 'A', 'account_type_key' => 'P', 'is_group' => 0, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'IPSFA', 'key' => '21040204', 'parent_key' => '210402', 'balance_type' => 'A', 'account_type_key' => 'P', 'is_group' => 0, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'Retención de Impuesto Sobre la Renta', 'key' => '210403', 'parent_key' => '2104', 'balance_type' => 'A', 'account_type_key' => 'P', 'is_group' => 0, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'Retención  F. S. V.', 'key' => '210404', 'parent_key' => '2104', 'balance_type' => 'A', 'account_type_key' => 'P', 'is_group' => 0, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'Órdenes de Descuentos – Bancos y Otras Financieras', 'key' => '210405', 'parent_key' => '2104', 'balance_type' => 'A', 'account_type_key' => 'P', 'is_group' => 0, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'Procuraduría General de la República', 'key' => '210406', 'parent_key' => '2104', 'balance_type' => 'A', 'account_type_key' => 'P', 'is_group' => 0, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'Otras Retenciones', 'key' => '210407', 'parent_key' => '2104', 'balance_type' => 'A', 'account_type_key' => 'P', 'is_group' => 0, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'IMPUESTO SOBRE LA RENTA POR PAGAR', 'key' => '2105', 'parent_key' => '21', 'balance_type' => 'A', 'account_type_key' => 'P', 'is_group' => 1, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'Impuesto sobre la Renta por Pagar', 'key' => '210501', 'parent_key' => '2105', 'balance_type' => 'A', 'account_type_key' => 'P', 'is_group' => 0, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'OBLIGACIONES POR ARRENDAMIENTO FINANCIERO (CORTO PLAZO)', 'key' => '2106', 'parent_key' => '21', 'balance_type' => 'A', 'account_type_key' => 'P', 'is_group' => 1, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'Obligaciones por Arrendamiento Financiero', 'key' => '210601', 'parent_key' => '2106', 'balance_type' => 'A', 'account_type_key' => 'P', 'is_group' => 0, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'IVA - DÉBITO FISCAL', 'key' => '2107', 'parent_key' => '21', 'balance_type' => 'A', 'account_type_key' => 'P', 'is_group' => 1, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'Débito Fiscal sobre Ventas - IVA', 'key' => '210701', 'parent_key' => '2107', 'balance_type' => 'A', 'account_type_key' => 'P', 'is_group' => 0, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'IVA Retenido a Terceros', 'key' => '210702', 'parent_key' => '2107', 'balance_type' => 'A', 'account_type_key' => 'P', 'is_group' => 0, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'CUENTAS POR PAGAR – PARTES RELACIONADAS', 'key' => '2108', 'parent_key' => '21', 'balance_type' => 'A', 'account_type_key' => 'P', 'is_group' => 1, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'Dividendos por Pagar - Accionistas', 'key' => '210801', 'parent_key' => '2108', 'balance_type' => 'A', 'account_type_key' => 'P', 'is_group' => 0, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'NO CORRIENTE', 'key' => '22', 'parent_key' => '2', 'balance_type' => 'A', 'account_type_key' => 'P', 'is_group' => 1, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'PRÉSTAMOS POR PAGAR A LARGO PLAZO', 'key' => '2201', 'parent_key' => '22', 'balance_type' => 'A', 'account_type_key' => 'P', 'is_group' => 1, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'Préstamos Bancarios (Porción a Largo Plazo)', 'key' => '220101', 'parent_key' => '2201', 'balance_type' => 'A', 'account_type_key' => 'P', 'is_group' => 0, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'OBLIGACIONES POR ARRENDAMIENTO FINANCIERO LARGO PLAZO', 'key' => '2202', 'parent_key' => '22', 'balance_type' => 'A', 'account_type_key' => 'P', 'is_group' => 1, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'Obligaciones por Arrendamiento Financiero', 'key' => '220201', 'parent_key' => '2202', 'balance_type' => 'A', 'account_type_key' => 'P', 'is_group' => 0, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'PROVISIÓN PARA OBLIGACIONES LABORALES', 'key' => '2203', 'parent_key' => '22', 'balance_type' => 'A', 'account_type_key' => 'P', 'is_group' => 1, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'Indemnizaciones', 'key' => '220301', 'parent_key' => '2203', 'balance_type' => 'A', 'account_type_key' => 'P', 'is_group' => 0, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'Prestación Económica por Renuncia Voluntaria', 'key' => '220302', 'parent_key' => '2203', 'balance_type' => 'A', 'account_type_key' => 'P', 'is_group' => 0, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'Prestaciones de Ley', 'key' => '220303', 'parent_key' => '2203', 'balance_type' => 'A', 'account_type_key' => 'P', 'is_group' => 0, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'PASIVO POR IMPUESTO SOBRE LA RENTA DIFERIDO', 'key' => '2204', 'parent_key' => '22', 'balance_type' => 'A', 'account_type_key' => 'P', 'is_group' => 1, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'Pasivo por Impuesto sobre la Renta Diferido', 'key' => '220401', 'parent_key' => '2204', 'balance_type' => 'A', 'account_type_key' => 'P', 'is_group' => 0, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'PATRIMONIO', 'key' => '3', 'parent_key' => '', 'balance_type' => 'A', 'account_type_key' => 'K', 'is_group' => 1, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'CAPITAL Y RESERVAS', 'key' => '31', 'parent_key' => '3', 'balance_type' => 'A', 'account_type_key' => 'K', 'is_group' => 1, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'CAPITAL', 'key' => '3101', 'parent_key' => '31', 'balance_type' => 'A', 'account_type_key' => 'K', 'is_group' => 1, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'Capital', 'key' => '310101', 'parent_key' => '3101', 'balance_type' => 'A', 'account_type_key' => 'K', 'is_group' => 0, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'RESERVA LEGAL', 'key' => '3102', 'parent_key' => '31', 'balance_type' => 'A', 'account_type_key' => 'K', 'is_group' => 1, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'Reserva Legal', 'key' => '310201', 'parent_key' => '3102', 'balance_type' => 'A', 'account_type_key' => 'K', 'is_group' => 0, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'UTILIDADES DE EJERCICIOS ANTERIORES', 'key' => '3103', 'parent_key' => '31', 'balance_type' => 'A', 'account_type_key' => 'K', 'is_group' => 1, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'Utilidades de Ejercicios Anteriores', 'key' => '310301', 'parent_key' => '3103', 'balance_type' => 'A', 'account_type_key' => 'K', 'is_group' => 0, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'UTILIDAD DE EJERCICIO ACTUAL', 'key' => '3104', 'parent_key' => '31', 'balance_type' => 'A', 'account_type_key' => 'K', 'is_group' => 1, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'Utilidades de Ejercicio Actual', 'key' => '310401', 'parent_key' => '3104', 'balance_type' => 'A', 'account_type_key' => 'K', 'is_group' => 0, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'DÉFICIT DE EJERCICIOS ANTERIORES', 'key' => '3105', 'parent_key' => '31', 'balance_type' => 'A', 'account_type_key' => 'K', 'is_group' => 1, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'Déficit de Ejercicios Anteriores', 'key' => '310501', 'parent_key' => '3105', 'balance_type' => 'A', 'account_type_key' => 'K', 'is_group' => 0, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'DÉFICIT DE EJERCICIO ACTUAL', 'key' => '3106', 'parent_key' => '31', 'balance_type' => 'A', 'account_type_key' => 'K', 'is_group' => 1, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'Déficit de Ejercicio Actual', 'key' => '310601', 'parent_key' => '3106', 'balance_type' => 'A', 'account_type_key' => 'K', 'is_group' => 0, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'CUENTAS DE RESULTADO DEUDORAS', 'key' => '4', 'parent_key' => '', 'balance_type' => 'D', 'account_type_key' => 'C', 'is_group' => 1, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'COSTOS Y GASTOS DE OPERACIÓN', 'key' => '41', 'parent_key' => '4', 'balance_type' => 'D', 'account_type_key' => 'C', 'is_group' => 1, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'COSTO DE VENTAS', 'key' => '4101', 'parent_key' => '41', 'balance_type' => 'D', 'account_type_key' => 'C', 'is_group' => 1, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'Costo de Ventas de Servicios', 'key' => '410101', 'parent_key' => '4101', 'balance_type' => 'D', 'account_type_key' => 'C', 'is_group' => 0, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'Costo de Ventas de Mercaderías', 'key' => '410102', 'parent_key' => '4101', 'balance_type' => 'D', 'account_type_key' => 'C', 'is_group' => 0, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'Otros Costos de Venta', 'key' => '410103', 'parent_key' => '4101', 'balance_type' => 'D', 'account_type_key' => 'C', 'is_group' => 0, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'GASTOS DE VENTAS', 'key' => '4102', 'parent_key' => '41', 'balance_type' => 'D', 'account_type_key' => 'G', 'is_group' => 1, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'Sueldos y Salarios', 'key' => '410201', 'parent_key' => '4102', 'balance_type' => 'D', 'account_type_key' => 'G', 'is_group' => 0, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'Comisiones', 'key' => '410202', 'parent_key' => '4102', 'balance_type' => 'D', 'account_type_key' => 'G', 'is_group' => 0, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'Horas Extras', 'key' => '410203', 'parent_key' => '4102', 'balance_type' => 'D', 'account_type_key' => 'G', 'is_group' => 0, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'Vacaciones', 'key' => '410204', 'parent_key' => '4102', 'balance_type' => 'D', 'account_type_key' => 'G', 'is_group' => 0, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'Aguinaldos', 'key' => '410205', 'parent_key' => '4102', 'balance_type' => 'D', 'account_type_key' => 'G', 'is_group' => 0, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'Bonificaciones y Gratificaciones', 'key' => '410206', 'parent_key' => '4102', 'balance_type' => 'D', 'account_type_key' => 'G', 'is_group' => 0, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'Indemnizaciones', 'key' => '410207', 'parent_key' => '4102', 'balance_type' => 'D', 'account_type_key' => 'G', 'is_group' => 0, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'Cuota Patronal I.S.S.S', 'key' => '410208', 'parent_key' => '4102', 'balance_type' => 'D', 'account_type_key' => 'G', 'is_group' => 0, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'Cuota Patronal  A.F.P.', 'key' => '410209', 'parent_key' => '4102', 'balance_type' => 'D', 'account_type_key' => 'G', 'is_group' => 0, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'Otras Prestaciones al Personal', 'key' => '410210', 'parent_key' => '4102', 'balance_type' => 'D', 'account_type_key' => 'G', 'is_group' => 0, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'Honorarios', 'key' => '410211', 'parent_key' => '4102', 'balance_type' => 'D', 'account_type_key' => 'G', 'is_group' => 0, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'Papelería y Útiles', 'key' => '410212', 'parent_key' => '4102', 'balance_type' => 'D', 'account_type_key' => 'G', 'is_group' => 0, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'Teléfono y Correo', 'key' => '410213', 'parent_key' => '4102', 'balance_type' => 'D', 'account_type_key' => 'G', 'is_group' => 0, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'Servicio Eléctrico', 'key' => '410214', 'parent_key' => '4102', 'balance_type' => 'D', 'account_type_key' => 'G', 'is_group' => 0, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'Servicio de Agua', 'key' => '410215', 'parent_key' => '4102', 'balance_type' => 'D', 'account_type_key' => 'G', 'is_group' => 0, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'Impuestos Fiscales y Municipales', 'key' => '410216', 'parent_key' => '4102', 'balance_type' => 'D', 'account_type_key' => 'G', 'is_group' => 0, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'Fletes y Transportes', 'key' => '410217', 'parent_key' => '4102', 'balance_type' => 'D', 'account_type_key' => 'G', 'is_group' => 0, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'Reparación y Mantenimiento de Instalaciones', 'key' => '410218', 'parent_key' => '4102', 'balance_type' => 'D', 'account_type_key' => 'G', 'is_group' => 0, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'Reparación y Mantenimiento de Mob. y Equipo', 'key' => '410219', 'parent_key' => '4102', 'balance_type' => 'D', 'account_type_key' => 'G', 'is_group' => 0, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'Reparación y Mantenimiento de Vehículos', 'key' => '410220', 'parent_key' => '4102', 'balance_type' => 'D', 'account_type_key' => 'G', 'is_group' => 0, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'Combustibles y Lubricantes', 'key' => '410221', 'parent_key' => '4102', 'balance_type' => 'D', 'account_type_key' => 'G', 'is_group' => 0, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'Publicidad y Promociones', 'key' => '410222', 'parent_key' => '4102', 'balance_type' => 'D', 'account_type_key' => 'G', 'is_group' => 0, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'Viáticos y Gastos de Viaje', 'key' => '410223', 'parent_key' => '4102', 'balance_type' => 'D', 'account_type_key' => 'G', 'is_group' => 0, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'Alquiler de Local', 'key' => '410224', 'parent_key' => '4102', 'balance_type' => 'D', 'account_type_key' => 'G', 'is_group' => 0, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'Arrendamiento de Equipo', 'key' => '410225', 'parent_key' => '4102', 'balance_type' => 'D', 'account_type_key' => 'G', 'is_group' => 0, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'Cuotas y Suscripciones', 'key' => '410226', 'parent_key' => '4102', 'balance_type' => 'D', 'account_type_key' => 'G', 'is_group' => 0, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'Seguros', 'key' => '410227', 'parent_key' => '4102', 'balance_type' => 'D', 'account_type_key' => 'G', 'is_group' => 0, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'Depreciaciones', 'key' => '410228', 'parent_key' => '4102', 'balance_type' => 'D', 'account_type_key' => 'G', 'is_group' => 0, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'Servicio de Vigilancia', 'key' => '410229', 'parent_key' => '4102', 'balance_type' => 'D', 'account_type_key' => 'G', 'is_group' => 0, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'Aseo y Limpieza', 'key' => '410230', 'parent_key' => '4102', 'balance_type' => 'D', 'account_type_key' => 'G', 'is_group' => 0, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'Artículos Promocionales', 'key' => '410231', 'parent_key' => '4102', 'balance_type' => 'D', 'account_type_key' => 'G', 'is_group' => 0, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'GASTOS DE ADMINISTRACIÓN', 'key' => '4103', 'parent_key' => '41', 'balance_type' => 'D', 'account_type_key' => 'G', 'is_group' => 1, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'Sueldos', 'key' => '410301', 'parent_key' => '4103', 'balance_type' => 'D', 'account_type_key' => 'G', 'is_group' => 0, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'Horas Extras', 'key' => '410302', 'parent_key' => '4103', 'balance_type' => 'D', 'account_type_key' => 'G', 'is_group' => 0, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'Vacaciones', 'key' => '410303', 'parent_key' => '4103', 'balance_type' => 'D', 'account_type_key' => 'G', 'is_group' => 0, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'Aguinaldos', 'key' => '410304', 'parent_key' => '4103', 'balance_type' => 'D', 'account_type_key' => 'G', 'is_group' => 0, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'Bonificaciones y Gratificaciones', 'key' => '410305', 'parent_key' => '4103', 'balance_type' => 'D', 'account_type_key' => 'G', 'is_group' => 0, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'Indemnizaciones', 'key' => '410306', 'parent_key' => '4103', 'balance_type' => 'D', 'account_type_key' => 'G', 'is_group' => 0, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'Cuota Patronal I.S.S.S', 'key' => '410307', 'parent_key' => '4103', 'balance_type' => 'D', 'account_type_key' => 'G', 'is_group' => 0, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'Cuota Patronal  A.F.P.', 'key' => '410308', 'parent_key' => '4103', 'balance_type' => 'D', 'account_type_key' => 'G', 'is_group' => 0, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'Otras Prestaciones al Personal', 'key' => '410309', 'parent_key' => '4103', 'balance_type' => 'D', 'account_type_key' => 'G', 'is_group' => 0, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'Honorarios', 'key' => '410310', 'parent_key' => '4103', 'balance_type' => 'D', 'account_type_key' => 'G', 'is_group' => 0, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'Papelería y Útiles', 'key' => '410311', 'parent_key' => '4103', 'balance_type' => 'D', 'account_type_key' => 'G', 'is_group' => 0, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'Teléfono y Correo', 'key' => '410312', 'parent_key' => '4103', 'balance_type' => 'D', 'account_type_key' => 'G', 'is_group' => 0, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'Servicio Eléctrico', 'key' => '410313', 'parent_key' => '4103', 'balance_type' => 'D', 'account_type_key' => 'G', 'is_group' => 0, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'Servicio de Agua', 'key' => '410314', 'parent_key' => '4103', 'balance_type' => 'D', 'account_type_key' => 'G', 'is_group' => 0, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'Impuestos Fiscales y Municipales', 'key' => '410315', 'parent_key' => '4103', 'balance_type' => 'D', 'account_type_key' => 'G', 'is_group' => 0, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'Fletes y Transportes', 'key' => '410316', 'parent_key' => '4103', 'balance_type' => 'D', 'account_type_key' => 'G', 'is_group' => 0, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'Reparación y Mantenimiento de Instalaciones', 'key' => '410317', 'parent_key' => '4103', 'balance_type' => 'D', 'account_type_key' => 'G', 'is_group' => 0, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'Reparación y Mantenimiento de Mob. y Equipo', 'key' => '410318', 'parent_key' => '4103', 'balance_type' => 'D', 'account_type_key' => 'G', 'is_group' => 0, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'Reparación y Mantenimiento de Vehículos', 'key' => '410319', 'parent_key' => '4103', 'balance_type' => 'D', 'account_type_key' => 'G', 'is_group' => 0, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'Combustibles y Lubricantes', 'key' => '410320', 'parent_key' => '4103', 'balance_type' => 'D', 'account_type_key' => 'G', 'is_group' => 0, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'Aseo y Limpieza', 'key' => '410321', 'parent_key' => '4103', 'balance_type' => 'D', 'account_type_key' => 'G', 'is_group' => 0, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'Viáticos y Gastos de Viaje', 'key' => '410322', 'parent_key' => '4103', 'balance_type' => 'D', 'account_type_key' => 'G', 'is_group' => 0, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'Alquiler de Local', 'key' => '410323', 'parent_key' => '4103', 'balance_type' => 'D', 'account_type_key' => 'G', 'is_group' => 0, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'Arrendamiento de Equipo', 'key' => '410324', 'parent_key' => '4103', 'balance_type' => 'D', 'account_type_key' => 'G', 'is_group' => 0, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'Cuotas y Suscripciones', 'key' => '410325', 'parent_key' => '4103', 'balance_type' => 'D', 'account_type_key' => 'G', 'is_group' => 0, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'Seguros', 'key' => '410326', 'parent_key' => '4103', 'balance_type' => 'D', 'account_type_key' => 'G', 'is_group' => 0, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'Depreciaciones', 'key' => '410327', 'parent_key' => '4103', 'balance_type' => 'D', 'account_type_key' => 'G', 'is_group' => 0, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'Servicio de Vigilancia', 'key' => '410328', 'parent_key' => '4103', 'balance_type' => 'D', 'account_type_key' => 'G', 'is_group' => 0, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'Otros', 'key' => '410329', 'parent_key' => '4103', 'balance_type' => 'D', 'account_type_key' => 'G', 'is_group' => 0, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'COSTOS Y GASTOS DE NO OPERACIÓN', 'key' => '42', 'parent_key' => '4', 'balance_type' => 'D', 'account_type_key' => 'G', 'is_group' => 1, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'COSTOS FINANCIEROS', 'key' => '4201', 'parent_key' => '42', 'balance_type' => 'D', 'account_type_key' => 'G', 'is_group' => 1, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'Intereses', 'key' => '420101', 'parent_key' => '4201', 'balance_type' => 'D', 'account_type_key' => 'G', 'is_group' => 0, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'Comisiones', 'key' => '420102', 'parent_key' => '4201', 'balance_type' => 'D', 'account_type_key' => 'G', 'is_group' => 0, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'Honorarios', 'key' => '420103', 'parent_key' => '4201', 'balance_type' => 'D', 'account_type_key' => 'G', 'is_group' => 0, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'Seguros', 'key' => '420104', 'parent_key' => '4201', 'balance_type' => 'D', 'account_type_key' => 'G', 'is_group' => 0, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'Otros', 'key' => '420105', 'parent_key' => '4201', 'balance_type' => 'D', 'account_type_key' => 'G', 'is_group' => 0, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'PÉRDIDA EN VENTA O RETIRO DE ACTIVOS FIJOS', 'key' => '4202', 'parent_key' => '42', 'balance_type' => 'D', 'account_type_key' => 'G', 'is_group' => 1, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'Pérdida en Venta o Retiro de Activos Fijos', 'key' => '420201', 'parent_key' => '4202', 'balance_type' => 'D', 'account_type_key' => 'G', 'is_group' => 0, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'GASTOS POR DETERIORO DE VALOR DE ACTIVOS', 'key' => '4203', 'parent_key' => '42', 'balance_type' => 'D', 'account_type_key' => 'G', 'is_group' => 1, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'Gastos por Deterioro de Valor de Activos', 'key' => '420301', 'parent_key' => '4203', 'balance_type' => 'D', 'account_type_key' => 'G', 'is_group' => 0, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'GASTOS POR DETERIORO EN EL VALOR DE LAS INVERSIONES', 'key' => '4204', 'parent_key' => '42', 'balance_type' => 'D', 'account_type_key' => 'G', 'is_group' => 1, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'Gastos por Deterioro de Valor de las Inversiones', 'key' => '420401', 'parent_key' => '4204', 'balance_type' => 'D', 'account_type_key' => 'G', 'is_group' => 0, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'PÉRDIDAS EN VALOR RAZONABLE DE LAS PROPIEDADES DE INVERSIÓN', 'key' => '4205', 'parent_key' => '42', 'balance_type' => 'D', 'account_type_key' => 'G', 'is_group' => 1, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'Pérdida en Valor Razonable de las Propiedades', 'key' => '420501', 'parent_key' => '4205', 'balance_type' => 'D', 'account_type_key' => 'G', 'is_group' => 0, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'GASTOS DE EJERCICIOS ANTERIORES', 'key' => '4206', 'parent_key' => '42', 'balance_type' => 'D', 'account_type_key' => 'G', 'is_group' => 1, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'Gastos de Ejercicios Anteriores', 'key' => '420601', 'parent_key' => '4206', 'balance_type' => 'D', 'account_type_key' => 'G', 'is_group' => 0, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'GASTOS POR OPERACIONES EN DISCONTINUACIÓN', 'key' => '4207', 'parent_key' => '42', 'balance_type' => 'D', 'account_type_key' => 'G', 'is_group' => 1, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'Gastos por Operaciones en Discontinuación ', 'key' => '420701', 'parent_key' => '4207', 'balance_type' => 'D', 'account_type_key' => 'G', 'is_group' => 0, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'OTROS GASTOS DE NO OPERACIÓN', 'key' => '4208', 'parent_key' => '42', 'balance_type' => 'D', 'account_type_key' => 'G', 'is_group' => 1, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'Otros Gastos de no Operación ', 'key' => '420801', 'parent_key' => '4208', 'balance_type' => 'D', 'account_type_key' => 'G', 'is_group' => 0, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'CUENTAS DE RESULTADO ACREEDORAS', 'key' => '5', 'parent_key' => '', 'balance_type' => 'A', 'account_type_key' => 'I', 'is_group' => 1, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'INGRESOS DE ACTIVIDADES ORDINARIAS', 'key' => '51', 'parent_key' => '5', 'balance_type' => 'A', 'account_type_key' => 'I', 'is_group' => 1, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'SERVICIOS', 'key' => '5101', 'parent_key' => '51', 'balance_type' => 'A', 'account_type_key' => 'I', 'is_group' => 1, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'Ingresos por Prestación de Servicios', 'key' => '510101', 'parent_key' => '5101', 'balance_type' => 'A', 'account_type_key' => 'I', 'is_group' => 0, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'Otros Ingresos por Servicio', 'key' => '510102', 'parent_key' => '5101', 'balance_type' => 'A', 'account_type_key' => 'I', 'is_group' => 0, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'VENTAS', 'key' => '5102', 'parent_key' => '51', 'balance_type' => 'A', 'account_type_key' => 'Y', 'is_group' => 1, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'Venta de Mercaderías', 'key' => '510201', 'parent_key' => '5102', 'balance_type' => 'A', 'account_type_key' => 'Y', 'is_group' => 0, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'Otros Insumos', 'key' => '510202', 'parent_key' => '5102', 'balance_type' => 'A', 'account_type_key' => 'Y', 'is_group' => 0, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'INGRESOS DE ACTIVIDADES NO ORDINARIAS', 'key' => '52', 'parent_key' => '5', 'balance_type' => 'A', 'account_type_key' => 'Y', 'is_group' => 1, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'INGRESOS FINANCIEROS', 'key' => '5201', 'parent_key' => '52', 'balance_type' => 'A', 'account_type_key' => 'Y', 'is_group' => 1, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'Intereses Bancarios', 'key' => '520101', 'parent_key' => '5201', 'balance_type' => 'A', 'account_type_key' => 'Y', 'is_group' => 0, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'GANANCIA EN VENTA DE ACTIVOS FIJOS', 'key' => '5202', 'parent_key' => '52', 'balance_type' => 'A', 'account_type_key' => 'Y', 'is_group' => 1, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'Ganancia en Venta de Activos Fijos', 'key' => '520201', 'parent_key' => '5202', 'balance_type' => 'A', 'account_type_key' => 'Y', 'is_group' => 0, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'INGRESOS POR CAMBIO EN EL VALOR RAZONABLE DE LAS INVERSIONES', 'key' => '5203', 'parent_key' => '52', 'balance_type' => 'A', 'account_type_key' => 'Y', 'is_group' => 1, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'Ingreso por Cambio en el Valor Razonable de las Inversiones', 'key' => '520301', 'parent_key' => '5203', 'balance_type' => 'A', 'account_type_key' => 'Y', 'is_group' => 0, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'INGRESOS POR CAMBIO EN EL VALOR RAZONABLE DE LAS PROPIEDADES DE INVERSIÓN', 'key' => '5204', 'parent_key' => '52', 'balance_type' => 'A', 'account_type_key' => 'Y', 'is_group' => 1, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'Ingeresos por Cambio en el Valor Razonable de las Propiedades de Inversión', 'key' => '520401', 'parent_key' => '5204', 'balance_type' => 'A', 'account_type_key' => 'Y', 'is_group' => 0, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'INDEMNIZACIONES POR SINIESTROS', 'key' => '5205', 'parent_key' => '52', 'balance_type' => 'A', 'account_type_key' => 'Y', 'is_group' => 1, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'Indemnizaciones por Siniestros', 'key' => '520501', 'parent_key' => '5205', 'balance_type' => 'A', 'account_type_key' => 'Y', 'is_group' => 0, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'OTROS INGRESOS DE NO OPERACIÓN', 'key' => '5206', 'parent_key' => '52', 'balance_type' => 'A', 'account_type_key' => 'Y', 'is_group' => 1, 'account_chart_type_id' => 2));
		Account::create(array('name' => 'Otros Ingresos de no Operación', 'key' => '520601', 'parent_key' => '5206', 'balance_type' => 'A', 'account_type_key' => 'Y', 'is_group' => 0, 'account_chart_type_id' => 2));
	}

}
